# Generated by Django 4.0.6 on 2022-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES'), ('TRAVEL', 'TRAVEL'), ('FOOD', 'FOOD'), ('RENT', 'RENT'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('BILLS', 'BILLS'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
