# Generated by Django 4.0.6 on 2022-08-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('BUSINESS', 'BUSINESS'), ('SIDE-HUSTLES', 'SIDE-HUSTLES'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
